[tools]
node = 'lts'
deno = 'latest'
python = "3.11.8"
go = "1.22.1"
bun = "latest"


[tasks.python]
description = "Install neovim & pynvim @pip"
run = "pip install -U pip && pip install neovim pynvim"

[tasks.node]
description = "Install neovim @npm"
run = "npm install -g neovim"

[tasks.ghq]
description = "Install ghq"
run = "go install github.com/x-motemen/ghq@latest"

[tasks.rust]
description = "Install rust"
run = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh"

[tasks.bat]
description = "Install bat"
run = "sudo apt install bat -y && mkdir -p ~/.local/bin && ln -s /usr/bin/batcat ~/.local/bin/bat"

[tasks.setup]
description = "Setup"
depends = ["ghq", "node", "python", "rust", "bat"]


[settings]
experimental = true
