general.live_config_reload = true
general.import = [
  "~/.config/alacritty/color.toml",
  "~/.config/alacritty/keybinding.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 4, y = 2 }
opacity = 0.9
blur = true
startup_mode = "Fullscreen"

[font]
size = 13
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"

[colors.vi_mode_cursor]
text = "#E78284"

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }
