[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "n"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "n"
mods = "Shift"
mode = "Search|~Vi"
