[greenclip]
max_history_length = 250
max_selection_size_bytes = 0
blacklisted_applications = []
enable_image_support = true
history_file = "/home/syamaguc/.cache/greenclip.history"
image_cache_directory = "/tmp/greenclip"
trim_space_from_selection = true
use_primary_selection_as_input = false
static_history = ['''¯\_(ツ)_/¯''', 'https://github.com/syamaguc/config']
