#!/usr/bin/env sh

spacebar -m config position bottom
spacebar -m config height 27
spacebar -m config title on
spacebar -m config spaces on
spacebar -m config clock on
spacebar -m config power on
spacebar -m config padding_left 20
spacebar -m config padding_right 20
spacebar -m config spacing_left 25
spacebar -m config spacing_right 15
spacebar -m config text_font "Menlo:Regular:12.0"
spacebar -m config icon_font "Font Awesome 5 Free:Solid:12.0"
spacebar -m config background_color 0xff282a36
spacebar -m config foreground_color 0xfff8f8f2
spacebar -m config power_icon_color 0xff50fa7b
spacebar -m config battery_icon_color 0xffffb86c
spacebar -m config dnd_icon_color 0xff8be9fd
spacebar -m config clock_icon_color 0xffff79c6
spacebar -m config space_icon_color 0xff50fa7b
spacebar -m config space_icon_color_secondary 0xfff1fa8c
spacebar -m config space_icon_color_tertiary 0xffff5555
spacebar -m config space_icon_strip 1 2 3 4 5 6 7 8 9 10
spacebar -m config power_icon_strip 🔋
spacebar -m config space_icon •
spacebar -m config clock_icon 🕰️
spacebar -m config dnd_icon 🌙
spacebar -m config clock_format "%Y/%m/%d %H:%M"
spacebar -m config right_shell on
spacebar -m config right_shell_icon 🫂
spacebar -m config right_shell_command "whoami"

echo "spacebar configuration loaded.."
