name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contaner-test:
    name: Container - ${{ matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["archlinux:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4
      - name: setup script
        run: |
          bash ./script/setup.sh
        shell: bash

      - name: stow link
        run: |
          make link
        shell: bash

  os-test:
    name: OS - ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup script
        run: |
          bash ./script/setup.sh
        shell: bash
      - name: stow link
        run: |
          make link
        shell: bash
