name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  contaner-test:
    name: Container - ${{ matrix.container }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: ["archlinux:latest"]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v4
      - name: setup script
        run: |
          if [ "${{ matrix.container }}" = "archlinux:latest" ]; then
            bash ./script/setup.sh
          fi
        shell: bash

      - name: install packages
        run: |
          if [ "${{ matrix.container }}" = "archlinux:latest" ]; then
            make detect
          fi
        shell: bash

      - name: Build with source
        run: |
          printenv
        shell: bash

  os-test:
    name: OS - ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: setup script
        run: |
          bash ./script/setup.sh
        shell: bash
      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            make detect
          elif [ "${{ runner.os }}" = "macOS" ]; then
            make detect
          fi
        shell: bash
